/* Artist workspace; no secrets, API caches or simulated production records. */
(() => {
 'use strict';
 const API='https://tqwaepvdsvyyfgtlurkm.supabase.co/functions/v1/artist-workspace';
 const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n||0)/100);
 const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin'}).format(new Date());
 const date=s=>s?new Date(s.length===10?s+'T12:00:00':s).toLocaleDateString('de-DE',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Berlin'}):'Ohne Termin';
 const link=s=>{try{return new URL(s).protocol==='https:'?s:'';}catch{return '';}};
 const badge=(s,style='')=>`<span class="badge ${style}">${E(s)}</span>`;
 const empty=s=>`<div class="app-empty">${E(s)}</div>`;
 const button=(text,action,id='',primary=false)=>`<button type="button" class="app-btn ${primary?'primary':''}" data-app="${action}" data-id="${E(id)}">${E(text)}</button>`;
 const paths={today:'M3 10 12 3l9 7M5 9v12h5v-7h4v7h5V9',contacts:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M17 4a4 4 0 0 1 0 8M22 21v-2a4 4 0 0 0-3-4',bookings:'M8 2v4m8-4v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2',content:'M4 3h16v18H4zM10 8l6 4-6 4z',results:'M4 20h17M7 16v-4m5 4V5m5 11V8'};
 const names={today:'Heute',contacts:'Kontakte',bookings:'Buchungen',content:'Inhalte',results:'Ergebnisse'};
 const state={d:null,tab:'today',segment:'all',query:'',bookFilter:'upcoming',contentFilter:'all',allTasks:false,ready:false,loading:false};
 let root,nav,dialog,saveHandler=null,draftKey='',toastTimer,renderGeneration=0;
 const authHeaders=()=>window.artistAuthHeaders?window.artistAuthHeaders():{'x-admin-key':KEY};
 async function api(body){if(!navigator.onLine)throw new Error('Du bist offline. Dein Entwurf bleibt erhalten. Bitte später speichern.');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Speichern fehlgeschlagen.');return d;}
 async function legacy(body){return state.ready?api({action:'legacy',payload:body}):post(body);}
 function toast(s){let t=document.getElementById('artistToast');if(!t){t=document.createElement('div');t.id='artistToast';t.setAttribute('role','status');document.body.append(t);}t.textContent=s;t.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.hidden=true,5000);}
 function init(){if(root)return;root=document.createElement('main');root.id='artistApp';root.hidden=true;document.querySelector('#wview').after(root);nav=document.createElement('nav');nav.id='artistNav';nav.setAttribute('aria-label','Hauptnavigation');nav.hidden=true;document.body.append(nav);dialog=document.createElement('dialog');dialog.id='artistDialog';document.body.append(dialog);
 root.addEventListener('click',onClick);nav.addEventListener('click',onClick);dialog.addEventListener('click',onClick);
 root.addEventListener('input',e=>{if(e.target.id==='appSearch'){state.query=e.target.value;renderList();}});
 dialog.addEventListener('input',saveDraft);dialog.addEventListener('change',saveDraft);
 dialog.addEventListener('cancel',saveDraft);
 dialog.addEventListener('submit',async e=>{e.preventDefault();if(!saveHandler)return;const btn=dialog.querySelector('[type=submit]');btn.disabled=true;dialog.querySelector('.form-error').textContent='';dialog.querySelector('.form-status').textContent='Wird gespeichert …';try{await saveHandler(new FormData(e.target));sessionStorage.removeItem(draftKey);dialog.close();history.replaceState(null,'','#'+state.tab);toast('Gespeichert');await load();}catch(err){dialog.querySelector('.form-error').textContent=err.message;dialog.querySelector('.form-status').textContent='Nicht gespeichert · Entwurf bleibt erhalten';btn.disabled=false;}});
 window.addEventListener('hashchange',()=>{if(!root.hidden){readRoute();render();}});
 window.addEventListener('offline',()=>{toast('Offline · Änderungen bleiben als Entwurf.');if(state.d)render();});window.addEventListener('online',()=>{toast('Wieder online. Bitte Änderungen speichern.');if(state.d)render();});
 }
 function readRoute(){const part=location.hash.replace('#','').split('/');state.tab=names[part[0]]?part[0]:'today';}
 window.hideArtistWorkspace=()=>{if(root){root.hidden=true;nav.hidden=true;}if(dialog?.open)dialog.close();};
 window.renderArtistWorkspace=async(base)=>{init();root.hidden=false;nav.hidden=false;document.querySelector('#wview').style.display='none';state.d=base;state.ready=!!base.app_ready;readRoute();if(base.role==='social'&&!['content','results'].includes(state.tab))state.tab='content';render();
 const version=++renderGeneration;if(state.ready){openRoute();return;}
 try{const full=await api({action:'dashboard'});if(version!==renderGeneration||root.hidden)return;state.d=full;state.ready=true;render();openRoute();}catch{if(version===renderGeneration){state.ready=false;render();openRoute();}}
 };
 function openRoute(){const [tab,id]=location.hash.slice(1).split('/');if(id&&!dialog.open){if(tab==='contacts')openContact(id);if(tab==='bookings')openGig(id);if(tab==='content')openContent(id);}}
 function changeTab(tab){state.tab=tab;location.hash=tab;render();window.scrollTo({top:0,behavior:'instant'});}
 const extNotice=()=>state.ready?'':'<div class="app-notice">Die neue Datenanbindung ist noch nicht freigeschaltet. Bestehende Kontakte, Auftritte und Rechnungen sind weiterhin erreichbar.</div>';
 function render(){if(!state.d)return;const social=state.d.role==='social';nav.innerHTML=Object.entries(names).filter(([k])=>!social||['content','results'].includes(k)).map(([k,v])=>`<button data-app="tab" data-id="${k}" ${k===state.tab?'aria-current="page"':''}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[k]}"/></svg>${v}</button>`).join('');
 const head=`<div class="app-topline"><span class="eyebrow">Warren Will / Artist workspace</span><span class="muted">${navigator.onLine?'● Online':'○ Offline'}</span></div>`;
 root.innerHTML=head+(!navigator.onLine?'<div class="app-notice">Offline · Angezeigter Stand bleibt sichtbar. Verbindliche Änderungen benötigen eine Online-Bestätigung.</div>':'')+({today:renderToday,contacts:renderContacts,bookings:renderBookings,content:renderContent,results:renderResults}[state.tab])();
 if(state.tab==='contacts')renderList();
 }
 const upcoming=()=> (state.d.gigs||[]).filter(g=>g.date>=today()&&g.booking_status!=='cancelled'&&g.booking_status!=='draft').sort((a,b)=>a.date.localeCompare(b.date));
 function tasks(){const d=state.d;const b=(d.board||[]).filter(x=>!x.archived_at&&!['done','approved','declined'].includes(x.status)&&(x.owner==='warren'||(!x.owner&&['ask','approval'].includes(x.kind)))).map(x=>({id:x.id,title:x.title,due:x.due_date,priority:x.priority,kind:'task',label:x.kind==='approval'?'Entscheidung ansehen':'Aufgabe öffnen'}));
 const contacts=(d.contacts||[]).filter(c=>!c.opt_out_at&&c.assigned_to==='warren'&&c.follow_up_date&&c.follow_up_date<=today()).map(c=>({id:c.id,title:c.next_action||'Bei '+c.name+' nachfassen',due:c.follow_up_date,kind:'contact',label:'Kontakt öffnen'}));
 const contents=(d.content||[]).filter(c=>c.approval==='waiting').map(c=>({id:c.id,title:c.title,kind:'content',label:'Inhalt freigeben',priority:'normal'}));
 return [...contacts,...b,...contents].sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')||({'high':0,'normal':1,'low':2}[a.priority||'normal']-{'high':0,'normal':1,'low':2}[b.priority||'normal']));}
 function renderToday(){const all=tasks(),n=upcoming()[0],d=state.d;return `<div class="app-titlebar"><div><div class="eyebrow">${new Date().toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'long',timeZone:'Europe/Berlin'})}</div><h1>Servus, Warren.</h1><p class="muted">Dein nächster Schritt. Dein nächster Auftritt.</p></div>${button('Aktualisieren','refresh')}</div>
 <div class="app-grid"><section class="app-card hero"><div class="eyebrow">Dein nächster Auftritt</div>${n?`<h3>${E(n.venues?.name||'Veranstaltungsort offen')}</h3><p>${date(n.date)} · ${E(n.venues?.city||'')}</p><p class="muted">${E(n.set_length||'Spielzeit noch offen')} · ${n.fee==null?'Gage offen':money(n.fee*100)}</p>${button('Buchung ansehen','gig',n.id,true)}`:'<h3>Platz für neue Dates.</h3><p class="muted">Noch kein kommender Auftritt eingetragen.</p>'+button('Auftritt eintragen','new-gig','',true)}</section>
 <section class="app-card"><div class="eyebrow">Diese Woche im Blick</div><div class="app-row"><div>Offene Aktionen für dich</div><b>${all.length}</b></div><div class="app-row"><div>Kommende Auftritte</div><b>${upcoming().length}</b></div><div class="app-row"><div>Inhalte zur Freigabe</div><b>${state.ready?(d.content||[]).filter(x=>x.approval==='waiting').length:'—'}</b></div></section></div>
 <h2>Das braucht dich${all.length?' · '+all.length:''}</h2>${all.length?`<div class="app-list">${(state.allTasks?all:all.slice(0,3)).map(x=>`<div class="app-row"><div>${x.due?`<span class="app-date">${x.due<today()?'Überfällig · ':''}${date(x.due)}</span>`:''}<h3>${E(x.title)}</h3></div>${button(x.label,x.kind,x.id)}</div>`).join('')}</div>`:empty('Für dich ist gerade nichts offen. Neue Aufgaben und Freigaben erscheinen hier.')}${all.length>3?`<div class="app-actions">${button(state.allTasks?'Weniger anzeigen':'Alle Aktionen anzeigen','all-tasks')}</div>`:''}
 <h2>Das Team arbeitet daran</h2><div class="app-list">${(d.board||[]).filter(x=>!x.archived_at&&['open','in_progress'].includes(x.status)&&(x.owner==='team'||x.owner==='lutho'||(!x.owner&&x.kind==='work'))).slice(0,4).map(x=>`<div class="app-row"><div><h3>${E(x.title)}</h3><span class="muted">${E(x.owner==='lutho'?'Lutho':'Team')}${x.due_date?' · '+date(x.due_date):''}</span></div>${badge(x.status==='in_progress'?'In Arbeit':'Offen','neutral')}</div>`).join('')||'<p class="muted">Keine offenen Team-Aufgaben.</p>'}</div>`;}
 function renderContacts(){return `<div class="app-titlebar"><div><div class="eyebrow">Beziehungen pflegen</div><h1>Kontakte</h1></div>${button('+ Kontakt','new-contact','',true)}</div><input id="appSearch" type="search" value="${E(state.query)}" placeholder="Name, Ort, E-Mail oder Segment" aria-label="Kontakte suchen"><div class="app-filters">${[['all','Alle'],['due','Heute nachfassen'],['waiting','Wartet auf Antwort'],['past','Frühere Veranstalter']].map(([k,n])=>`<button class="app-btn" data-app="segment" data-id="${k}" aria-pressed="${state.segment===k}">${n}</button>`).join('')}</div><div id="appContactList"></div>${state.d.role==='team'?`<div class="app-actions">${button('CSV von PhantomBuster importieren','import')}</div>`:''}`;}
 function contactRows(){return (state.d.contacts||[]).filter(c=>c.source!=='system-self').filter(c=>{const q=state.query.toLocaleLowerCase('de');if(q&&!JSON.stringify([c.name,c.email,c.venues?.name,c.venues?.city,c.tags]).toLocaleLowerCase('de').includes(q))return false;
 if(state.segment==='due')return !c.opt_out_at&&c.follow_up_date&&c.follow_up_date<=today();
 if(state.segment==='waiting')return ['contacted','waiting'].includes(c.status)||(state.d.pipeline||[]).some(o=>o.stage==='contacted'&&o.contacts?.name===c.name);
 if(state.segment==='past')return c.tags?.includes('Frühere Veranstalter')||c.status==='past_client'||(c.venues?.name&&(state.d.gigs||[]).some(g=>g.date<today()&&g.venues?.name===c.venues.name));return true;}).sort((a,b)=>a.name.localeCompare(b.name,'de'));}
 function renderList(){const list=document.getElementById('appContactList');if(!list)return;const rows=contactRows();list.innerHTML=`<p class="muted" role="status">${rows.length} Kontakte in der geladenen Liste</p>`+(rows.length?`<div class="app-list">${rows.map(c=>`<div class="app-row"><div><h3>${E(c.name)}</h3><p class="muted">${E(c.venues?.name||c.role||'Kontakt')}${c.venues?.city?' · '+E(c.venues.city):''}</p>${c.follow_up_date?badge('Nachfassen '+date(c.follow_up_date),c.follow_up_date<=today()?'attention':'neutral'):''}${c.opt_out_at?badge('Nicht kontaktieren','problem'):''}${(c.tags||[]).slice(0,2).map(t=>badge(t,'neutral')).join('')}</div>${button('Öffnen','contact',c.id)}</div>`).join('')}</div>`:empty('Keine passenden Kontakte. Suche oder Filter ändern.'));}
 function renderBookings(){const gigs=state.d.gigs||[];const list=state.bookFilter==='past'?gigs.filter(g=>g.date<today()).sort((a,b)=>b.date.localeCompare(a.date)):state.bookFilter==='all'?gigs:upcoming();return `<div class="app-titlebar"><div><div class="eyebrow">Auftritte & Vermietung</div><h1>Buchungen</h1></div>${button('+ Auftritt','new-gig','',true)}</div><div class="app-filters">${[['upcoming','Kommende'],['past','Vergangene'],['all','Alle'],['rentals','Equipment'],['invoices','Rechnungen']].map(([k,n])=>`<button class="app-btn" data-app="book-filter" data-id="${k}" aria-pressed="${state.bookFilter===k}">${n}</button>`).join('')}</div>${state.bookFilter==='rentals'?renderRentals():state.bookFilter==='invoices'?renderInvoices():list.length?`<div class="app-list">${list.map(g=>`<div class="app-row"><div><span class="app-date">${date(g.date)} · ${E(g.venues?.city||'')}</span><h3>${E(g.venues?.name||'Ort offen')}</h3><p class="muted">${E(g.set_length||'Spielzeit offen')} · ${g.fee==null?'Gage offen':money(g.fee*100)}</p>${badge(g.booking_status==='cancelled'?'Abgesagt':g.booking_status==='draft'?'Entwurf':'Bestätigt',g.booking_status==='cancelled'?'problem':'')}${state.ready?badge(g.is_public?'Auf Website':'Privat','neutral'):''}</div>${button('Details','gig',g.id)}</div>`).join('')}</div>`:empty('Keine Auftritte in dieser Ansicht.')}<p class="muted" style="margin-top:18px">Gagen sind vereinbarte Beträge. Zahlungseingänge und Kautionen werden separat geführt.</p>`;}
 function renderRentals(){if(!state.ready)return extNotice();return `<div class="app-actions" style="margin-bottom:16px">${button('+ Vermietung','rental','',true)}${state.d.role==='team'?button('Bestand bestätigen','inventory'):''}</div>${(state.d.inventory||[]).some(i=>i.quantity==null)?'<div class="app-notice">Stückzahlen noch nicht bestätigt. Entwürfe sind möglich; das Management muss den Bestand vor Reservierungen eintragen.</div>':''}${(state.d.rentals||[]).length?`<div class="app-list">${state.d.rentals.map(r=>`<div class="app-row"><div><span class="app-date">${date(r.starts_at)} – ${date(r.ends_at)}</span><h3>${E(r.customer_name)}</h3><p class="muted">${E(state.d.offers.find(o=>o.code===r.offer_code)?.name||r.offer_code)} · ${money(r.total_cents)}</p>${badge(({draft:'Entwurf',reserved:'Reserviert',collected:'Abgeholt',returned:'Zurückgegeben',cancelled:'Storniert'})[r.status])}${badge('Zahlung: '+({open:'offen',partial:'teilweise',paid:'bezahlt'})[r.payment_status],'neutral')}</div>${button('Details','rental',r.id)}</div>`).join('')}</div>`:empty('Noch keine Equipment-Buchungen. Preise und Bundles sind vorbereitet.')}`;}
 function invoiceCard(i){return `<div class="app-row"><div><h3>${E(i.invoice_number)}</h3><p class="muted">${E(i.recipient_name||i.venue_name||'Empfänger prüfen')} · ${money(i.gross_cents)}</p>${badge(({draft:'Entwurf',sent:'Versendet',paid:'Bezahlt',cancelled:'Storniert',storno:'Storno'})[i.status]||i.status,'neutral')}</div>${button('Prüfen','invoice',i.id)}</div>`;}
 function renderInvoices(){return(state.d.invoices||[]).length?`<div class="app-list">${state.d.invoices.map(invoiceCard).join('')}</div>`:empty('Noch keine Rechnungen. Rechnungsentwürfe werden bei der jeweiligen Buchung erstellt.');}
 function renderContent(){const d=state.d;const list=(d.content||[]).filter(c=>state.contentFilter==='all'||c.approval===state.contentFilter);return `<div class="app-titlebar"><div><div class="eyebrow">Vom Entwurf bis zum Beitrag</div><h1>Inhalte</h1></div>${d.role!=='client'?button('+ Inhalt','new-content','',true):''}</div>${extNotice()}<p class="muted">Freigaben erfolgen hier. Das Social-Team veröffentlicht über sein Planungstool und hinterlegt den Nachweis je Plattform.</p><div class="app-filters">${[['all','Alle'],['waiting','Zur Freigabe'],['approved','Freigegeben'],['changes','Änderungen']].map(([k,n])=>`<button class="app-btn" data-app="content-filter" data-id="${k}" aria-pressed="${state.contentFilter===k}">${n}</button>`).join('')}</div>${list.length?`<div class="app-grid">${list.map(c=>{const pubs=(d.publications||[]).filter(p=>p.content_id===c.id);return `<article class="app-card"><div class="eyebrow">Version ${c.version} · ${date(c.updated_at)}</div><h3 style="margin-top:10px">${E(c.title)}</h3>${badge(({draft:'Entwurf',waiting:'Wartet auf Warren',approved:'Freigegeben',changes:'Änderungen erbeten'})[c.approval],c.approval==='waiting'?'attention':'')}<p class="content-caption">${E(c.caption)}</p>${pubs.map(p=>`<div class="app-row"><div><b>${E(p.platform)}</b> ${p.version!==c.version?badge('Version '+p.version,'neutral'):''}<div class="muted">${({planned:'Geplant',published:'Veröffentlicht · manuell belegt',failed:'Fehlgeschlagen · Team prüft'})[p.status]}</div></div>${p.post_url&&link(p.post_url)?`<a class="app-btn" target="_blank" rel="noopener noreferrer" href="${E(link(p.post_url))}">Beitrag ↗</a>`:''}</div>`).join('')||'<p class="muted">Noch keine Veröffentlichung hinterlegt.</p>'}<div class="app-actions">${button(c.approval==='waiting'&&d.role==='client'?'Freigabe ansehen':'Details','content',c.id,c.approval==='waiting')}</div></article>`;}).join('')}</div>`:empty('Hier erscheinen vorbereitete Inhalte und ihre Veröffentlichungen. Noch keine Inhalte eingetragen.')}`;}
 function renderResults(){const d=state.d,year=today().slice(0,4);const gigs=(d.gigs||[]).filter(g=>g.date.startsWith(year)&&!['draft','cancelled'].includes(g.booking_status));const published=(d.publications||[]).filter(p=>p.status==='published');return `<div class="app-titlebar"><div><div class="eyebrow">Was sich bewegt</div><h1>Ergebnisse</h1><p class="muted">Quelle, Zeitraum und Datenstand bleiben sichtbar.</p></div>${d.role!=='client'?button('+ Kennzahl','metric'):''}</div>${d.role!=='social'?`<div class="stat-grid"><div class="app-card"><span class="muted">Gebuchte Gagen · ${year}</span><b class="stat-number">${money(gigs.reduce((s,g)=>s+Number(g.fee||0)*100,0))}</b><span class="muted">Vereinbart, kein Zahlungseingang</span></div><div class="app-card"><span class="muted">Als bezahlt markierte Rechnungen</span><b class="stat-number">${money((d.invoices||[]).filter(i=>i.status==='paid').reduce((s,i)=>s+i.gross_cents,0))}</b><span class="muted">Geladene Rechnungen · ohne Bankabgleich</span></div><div class="app-card"><span class="muted">Offene versendete Rechnungen</span><b class="stat-number">${money((d.invoices||[]).filter(i=>i.status==='sent').reduce((s,i)=>s+i.gross_cents,0))}</b><span class="muted">Entwürfe sind nicht enthalten</span></div></div>`:''}<h2>Veröffentlichungen</h2><div class="app-card"><b class="stat-number">${state.ready?published.length:'—'}</b><p>Hinterlegte Plattform-Veröffentlichungen</p><p class="muted">Mehrfachveröffentlichungen werden je Plattform gezählt. Keine Aussage über eindeutige Personen.</p></div><h2>Musik & Social</h2>${(d.metrics||[]).length?`<div class="app-grid">${d.metrics.map(m=>`<article class="app-card"><div class="eyebrow">${E(m.platform)}</div><h3>${E(m.metric)}</h3><b class="stat-number">${Number(m.value).toLocaleString('de-DE')}</b><p class="muted">${date(m.period_start)} – ${date(m.period_end)}</p><p class="muted">Manuell erfasst · Datenstand ${date(m.recorded_at)}</p>${Date.now()-Date.parse(m.recorded_at)>7*86400000?badge('Seit mehr als 7 Tagen nicht aktualisiert','attention'):''}<p class="muted">${E(m.note||'')}</p><a class="app-btn" href="${E(link(m.source_url))}" target="_blank" rel="noopener noreferrer">Quelle öffnen ↗</a></article>`).join('')}</div>`:empty('Noch keine verifizierten Kennzahlen. Fehlende Daten sind nicht null.')}
 <h2>Datenverbindungen</h2><div class="app-list">${['Social-Planungstool','YouTube Analytics','Spotify for Artists','Apple Music for Artists'].map(p=>`<div class="app-row"><div><h3>${p}</h3><span class="muted">${p==='Spotify for Artists'?'Verfügbaren Export bzw. Datenzugang prüfen':p==='Apple Music for Artists'?'Export kann als Quelle verwendet werden':'Kontoverbindung noch einzurichten'}</span></div>${badge('Nicht verbunden','neutral')}</div>`).join('')}</div><p class="muted" style="margin-top:16px">Stand CRM: ${date(d.generated_at)}. Die App behauptet keine automatische Messung ohne eingerichteten Zugang.</p>`;}
 function field(label,name,value='',type='text',extra=''){return `<label>${E(label)}<input name="${name}" type="${type}" value="${E(value)}" ${extra}></label>`;}
 function area(label,name,value='',extra=''){return `<label>${E(label)}<textarea name="${name}" rows="3" ${extra}>${E(value)}</textarea></label>`;}
 function select(label,name,options,value){return `<label>${E(label)}<select name="${name}">${options.map(([k,n])=>`<option value="${E(k)}" ${k===value?'selected':''}>${E(n)}</option>`).join('')}</select></label>`;}
 function saveDraft(){if(!dialog?.open||!draftKey)return;const values={};dialog.querySelectorAll('input[name],select[name],textarea[name]').forEach(el=>{if(!['file','password'].includes(el.type))values[el.name]=el.type==='checkbox'?el.checked:el.value;});try{sessionStorage.setItem(draftKey,JSON.stringify(values));}catch{dialog.querySelector('.form-status').textContent='Entwurfssicherung ist in diesem Browser nicht verfügbar.';}}
 function modal(title,html,handler=null,key=''){init();saveHandler=handler;draftKey=key?'ww-draft:'+state.d.role+':'+key:'';dialog.innerHTML=`<form><div class="dialog-inner"><div class="dialog-header"><h2>${E(title)}</h2>${button('Schließen','close')}</div>${html}<p class="form-error" role="alert"></p></div><div class="dialog-footer"><span class="form-status" role="status">${handler?'Entwurf · noch nicht gespeichert':''}</span>${handler?'<button class="primary" type="submit">Speichern</button>':button('Fertig','close')}</div></form>`;
 if(draftKey){try{const values=JSON.parse(sessionStorage.getItem(draftKey)||'null');if(values){dialog.querySelectorAll('[name]').forEach(el=>{if(values[el.name]!==undefined){if(el.type==='checkbox')el.checked=values[el.name];else if(el.type!=='file')el.value=values[el.name];}});dialog.querySelector('.form-status').textContent='Dein Entwurf wurde wiederhergestellt.';}}catch{}}
 if(!dialog.open)dialog.showModal();}
 function requiredReady(){if(state.ready)return true;modal('Datenanbindung noch offen',extNotice());return false;}
 function openContact(id){const c=(state.d.contacts||[]).find(x=>x.id===id);if(!c)return;const roleOptions=[['promoter','Promoter'],['booker','Booker'],['club_manager','Clubmanagement'],['dj','DJ'],['chef','Chef'],['other','Andere']];
 modal(c.name,`${c.opt_out_at?'<p class="form-error">Nicht kontaktieren · Opt-out ist hinterlegt.</p>':`<div class="app-actions">${c.phone_whatsapp?`<a class="app-btn" href="https://wa.me/${E(c.phone_whatsapp.replace(/\D/g,''))}" target="_blank" rel="noopener">WhatsApp öffnen</a>`:''}${c.email?`<a class="app-btn" href="mailto:${E(c.email)}">E-Mail öffnen</a>`:''}</div><p class="muted">Öffnet einen Entwurf. Die App versendet keine Nachricht automatisch.</p>`}
 ${field('Name','name',c.name,'text','required maxlength="120"')}${field('E-Mail','email',c.email,'email')}${field('WhatsApp / Telefon','phone_whatsapp',c.phone_whatsapp,'tel')}${select('Rolle','role',roleOptions,c.role)}${area('Kontaktnotiz','note',c.notes)}
 ${state.ready?`<div class="form-grid">${field('Wiedervorlage','follow_up_date',c.follow_up_date,'date')}${select('Zuständig','assigned_to',[['warren','Warren'],['team','Team']],c.assigned_to||'warren')}</div>${field('Nächster Schritt','next_action',c.next_action,'text','maxlength="300"')}${field('Segmente, mit Komma trennen','tags',(c.tags||[]).join(', '))}`:''}
 <h3 style="margin-top:24px">Gesprächsverlauf</h3><div id="appHistory" class="muted">${state.ready?'Wird geladen …':'Die vollständige Historie benötigt die neue Datenanbindung.'}</div>${state.ready?button('Gespräch dokumentieren','log',c.id):''}`,
 async fd=>{const payload=Object.fromEntries(fd);if(state.ready){await api({action:'save_contact',id,...payload,tags:String(payload.tags||'').split(',').map(t=>t.trim()).filter(Boolean)});}else await legacy({action:'update_contact',contact_id:id,...payload});},'contact:'+id);
 if(state.ready)api({action:'contact_history',id}).then(r=>{const el=document.getElementById('appHistory');if(el&&draftKey.endsWith(id))el.innerHTML=r.history.map(x=>`<p><b>${date(x.created_at)}</b><br>${E(x.summary)}</p>`).join('')||'Noch keine Gesprächsnotizen.';}).catch(()=>{const el=document.getElementById('appHistory');if(el)el.textContent='Verlauf konnte nicht geladen werden.';});}
 function newContact(){modal('Kontakt hinzufügen',field('Name','name','','text','required maxlength="120"')+field('E-Mail','email','','email')+field('Telefon / WhatsApp','phone_whatsapp','','tel')+select('Rolle','role',[['promoter','Promoter'],['booker','Booker'],['club_manager','Clubmanagement'],['dj','DJ'],['other','Andere']],'promoter')+area('Notiz','note'),async fd=>legacy({action:'add_contact',...Object.fromEntries(fd)}),'new-contact');}
 function openGig(id){const g=(state.d.gigs||[]).find(x=>x.id===id);if(!g)return;modal('Auftritt bearbeiten',`<div class="form-grid">${field('Datum','date',g.date,'date','required')}${field('Gage in €','fee',g.fee??'','number','min="0" step="0.01"')}</div>${field('Venue / Veranstaltung','venue_name',g.venues?.name,'text','required')}${field('Stadt','city',g.venues?.city)}${field('Spielzeit','set_length',g.set_length)}<label><input type="checkbox" name="deposit_received" ${g.deposit_received?'checked':''}> Anzahlung erhalten</label>${state.ready?select('Buchungsstatus','booking_status',[['confirmed','Bestätigt'],['draft','Entwurf'],['cancelled','Abgesagt']],g.booking_status||'confirmed')+`<label><input type="checkbox" name="is_public" ${g.is_public?'checked':''}> Auf der Website veröffentlichen</label><p class="muted">Öffentlich erscheinen nur bestätigte, freigegebene Termine. Gage und Kontaktdaten bleiben privat.</p>`:''}<h3 style="margin-top:22px">Rechnungen zu diesem Auftritt</h3>${(state.d.invoices||[]).filter(i=>i.gig_id===g.id).map(i=>`<p>${E(i.invoice_number)} · ${money(i.gross_cents)} ${button('Prüfen','invoice',i.id)}</p>`).join('')||'<p class="muted">Noch keine Rechnung verknüpft.</p>'}${state.d.role==='team'?button('Rechnungsentwurf erstellen','new-invoice',g.id):'<p class="muted">Das Management erstellt und versendet Rechnungen.</p>'}`,
 async fd=>{const b={id,date:fd.get('date'),fee:fd.get('fee')===''?null:Number(fd.get('fee')),venue_name:fd.get('venue_name'),city:fd.get('city'),set_length:fd.get('set_length'),deposit_received:fd.has('deposit_received')};
 if(state.ready)await api({action:'save_gig',...b,booking_status:fd.get('booking_status'),is_public:fd.has('is_public')});else await legacy({action:'edit_gig',...b});},'gig:'+id);}
 function newGig(){modal('Neuer bestätigter Auftritt',field('Datum','date','','date','required')+field('Venue / Veranstaltung','venue_name','','text','required')+field('Stadt','city')+field('Gage in €','fee','','number','min="0" step="0.01"')+field('Spielzeit','set_length')+'<p class="muted">Neue Termine werden zunächst privat gespeichert. Die Veröffentlichung erfolgt in den Buchungsdetails.</p>',async fd=>{const b=Object.fromEntries(fd);await legacy({action:'add_gig',...b,fee:b.fee===''?null:Number(b.fee)});},'new-gig');}
 function localTime(s){if(!s)return '';const d=new Date(s);const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
 function openRental(id){if(!requiredReady())return;const r=state.d.rentals.find(x=>x.id===id)||{id:crypto.randomUUID(),version:0,status:'draft',offer_code:'club',deposit_cents:0,deposit_status:'open',payment_status:'open'};
 modal(id?'Equipment-Buchung':'Equipment vermieten',`<input type="hidden" name="id" value="${r.id}"><input type="hidden" name="version" value="${r.version}">${field('Kunde / Veranstaltung','customer_name',r.customer_name,'text','required maxlength="120"')}${select('Kontakt verknüpfen','contact_id',[['','Kein Kontakt'],...(state.d.contacts||[]).filter(c=>c.source!=='system-self').map(c=>[c.id,c.name])],r.contact_id||'')}${select('Gerät oder Bundle · pro 24 Stunden','offer_code',state.d.offers.map(o=>[o.code,o.name+' · '+money(o.price_cents)]),r.offer_code)}<div class="form-grid">${field('Abholung','starts_at',localTime(r.starts_at),'datetime-local','required')}${field('Rückgabe','ends_at',localTime(r.ends_at),'datetime-local','required')}</div><p class="muted">Zeiten in der Zeitzone deines Geräts. Jeder angefangene Zeitraum von 24 Stunden zählt als Miettag. Die App prüft den verfügbaren Bestand beim Reservieren.</p>${select('Status','status',[['draft','Entwurf'],['reserved','Reserviert'],['collected','Abgeholt'],['returned','Zurückgegeben'],['cancelled','Storniert']],r.status)}<div class="form-grid">${field('Kaution in €','deposit',r.deposit_cents/100,'number','min="0" step="0.01"')}${select('Kaution','deposit_status',[['open','Noch offen'],['received','Erhalten'],['returned','Zurückgezahlt']],r.deposit_status)}</div>${select('Mietzahlung','payment_status',[['open','Offen'],['partial','Teilweise bezahlt'],['paid','Bezahlt']],r.payment_status)}${area('Übergabe / Notizen','notes',r.notes)}${id?`<p><b>Gespeicherter Mietpreis: ${money(r.total_cents)}</b> · zzgl. Kaution</p><p class="muted">Bei geänderten Mietzeiten wird der Preis beim Speichern neu berechnet.</p>${(state.d.invoices||[]).filter(i=>i.equipment_booking_id===r.id).map(i=>button(i.invoice_number,'invoice',i.id)).join('')}${state.d.role==='team'?button('Rechnungsentwurf erstellen','rental-invoice',r.id):''}`:''}`,
 async fd=>{const b=Object.fromEntries(fd);if(new Date(b.ends_at)<=new Date(b.starts_at))throw new Error('Rückgabe muss nach der Abholung liegen.');await api({action:'save_rental',...b,version:Number(b.version),starts_at:new Date(b.starts_at).toISOString(),ends_at:new Date(b.ends_at).toISOString(),deposit_cents:Math.round(Number(b.deposit)*100)});},'rental:'+(id||'new'));}
 function inventory(){if(!requiredReady())return;modal('Verfügbaren Bestand bestätigen','<p class="muted">Bitte physisch vorhandene und nutzbare Geräte zählen. Eine leere Stückzahl bedeutet „noch nicht geprüft“.</p>'+select('Gerät','code',state.d.inventory.map(i=>[i.code,i.name+' · '+(i.quantity==null?'ungeprüft':i.quantity+' Stück')]),state.d.inventory[0]?.code)+field('Bestätigte Stückzahl','quantity','','number','min="0" max="1000" step="1" required'),async fd=>api({action:'save_inventory',code:fd.get('code'),quantity:Number(fd.get('quantity'))}),'inventory');}
 function openContent(id){if(!requiredReady())return;const c=state.d.content.find(x=>x.id===id);if(!c)return;const artist=state.d.role==='client';const pubs=(state.d.publications||[]).filter(p=>p.content_id===id);modal(c.title,`<p class="muted">Version ${c.version} · ${date(c.updated_at)}</p>${link(c.preview_url)?`<a class="app-btn" href="${E(link(c.preview_url))}" target="_blank" rel="noopener noreferrer">Vorschau öffnen ↗</a>`:'<p class="muted">Noch keine Vorschau verlinkt.</p>'}<p style="white-space:pre-wrap">${E(c.caption)}</p>${c.review_note?`<p><b>Feedback:</b> ${E(c.review_note)}</p>`:''}${artist&&c.approval==='waiting'?select('Deine Entscheidung','approval',[['changes','Änderungen erbeten'],['approved','Freigeben']],'changes')+area('Feedback an das Team','review_note'):''}${!artist?`<div class="app-actions">${button('Neue Version bearbeiten','edit-content',id)}${button('Plattformstatus eintragen','publication',id)}</div>`:''}<h3 style="margin-top:24px">Veröffentlichungen & frühere Versionen</h3>${pubs.map(p=>`<p><b>${E(p.platform)} · Version ${p.version}</b><br>${E(({published:'Veröffentlicht',planned:'Geplant',failed:'Fehlgeschlagen'})[p.status])} · manuell erfasst<br>${E(p.note||'')}${link(p.post_url)?`<br><a href="${E(link(p.post_url))}" target="_blank" rel="noopener noreferrer">Beitrag öffnen ↗</a>`:''}</p>`).join('')||'<p class="muted">Noch keine Plattform-Einträge.</p>'}`,
 artist&&c.approval==='waiting'?async fd=>api({action:'review_content',id,version:c.version,approval:fd.get('approval'),review_note:fd.get('review_note')}):null,'review:'+id+':'+c.version);}
 function editContent(id){if(!requiredReady())return;const c=state.d.content.find(x=>x.id===id)||{id:crypto.randomUUID(),version:0,approval:'draft'};modal(id?'Neue Inhaltsversion':'Inhalt vorbereiten',`<input type="hidden" name="id" value="${c.id}"><input type="hidden" name="version" value="${c.version}">${field('Titel','title',c.title,'text','required maxlength="200"')}${field('HTTPS-Link zur Vorschau','preview_url',c.preview_url,'url')}${area('Caption / Text','caption',c.caption,'maxlength="5000"')}${select('Nächster Schritt','approval',[['draft','Als Entwurf speichern'],['waiting','Warren um Freigabe bitten']],'draft')}<p class="muted">Änderungen erzeugen eine neue Version. Eine frühere Freigabe gilt dafür nicht automatisch.</p>`,async fd=>api({action:'save_content',...Object.fromEntries(fd),version:Number(fd.get('version'))}),'content:'+(id||'new'));}
 function publication(id){if(!requiredReady())return;const c=state.d.content.find(x=>x.id===id);if(!c)return;modal('Plattform-Nachweis',`<p>${E(c.title)} · Version ${c.version}</p>${select('Plattform','platform',['Instagram','TikTok','YouTube','Facebook','Threads','LinkedIn'].map(x=>[x,x]),'Instagram')}${select('Status','status',[['planned','Geplant'],['published','Veröffentlicht'],['failed','Fehlgeschlagen']],'planned')}${field('Geplanter Zeitpunkt','scheduled_at','','datetime-local')}${field('Tatsächlich veröffentlicht am','published_at','','datetime-local')}${field('Link zum veröffentlichten Beitrag','post_url','','url')}${area('Notiz / Fehler','note')}<p class="muted">Manueller Nachweis. „Veröffentlicht“ erfordert Warrens Freigabe für diese Version und einen passenden Beitragslink. Diese Aktion veröffentlicht selbst keinen Beitrag.</p>`,async fd=>{const b=Object.fromEntries(fd);await api({action:'save_publication',...b,content_id:id,version:c.version,scheduled_at:b.scheduled_at?new Date(b.scheduled_at).toISOString():null,published_at:b.published_at?new Date(b.published_at).toISOString():null});},'publication:'+id+':'+c.version);}
 function metric(){if(!requiredReady())return;modal('Kennzahl mit Quelle erfassen',select('Plattform','platform',['YouTube','Spotify','Apple Music','Instagram','TikTok','Facebook'].map(x=>[x,x]),'YouTube')+field('Kennzahl, z. B. Playlist-Aufrufe','metric','','text','required maxlength="120"')+field('Gemessener Wert','value','','number','required min="0" step="any"')+`<div class="form-grid">${field('Zeitraum von','period_start','','date','required')}${field('Zeitraum bis','period_end','','date','required')}</div>`+field('Quellenlink zum Bericht oder Export','source_url','','url','required')+area('Definition / Hinweise','note')+'<p class="muted">Werte nur aus einem überprüften Bericht übernehmen. Videoaufrufe und Playlist-Aufrufe getrennt benennen.</p>',async fd=>api({action:'save_metric',...Object.fromEntries(fd),value:Number(fd.get('value'))}),'metric');}
 function task(id){const t=(state.d.board||[]).find(x=>x.id===id);if(!t)return;modal(t.title,`<p>${E(t.details||'')}</p>${t.price?`<p><b>${E(t.price)}</b></p>`:''}${t.due_date?`<p>Fällig: ${date(t.due_date)}</p>`:''}${t.kind==='approval'?select('Entscheidung','decision',[['','Bitte auswählen'],['approve','Freigeben'],['decline','Ablehnen']],''):select('Nächster Schritt','decision',[['comment','Kommentar speichern'],['ask_done','Als erledigt markieren']],'comment')}${area('Kommentar','comment')}${(t.comments||[]).map(c=>`<p class="muted"><b>${E(c.author)}</b>: ${E(c.body)}</p>`).join('')}`,
 async fd=>{const a=fd.get('decision'),comment=String(fd.get('comment')||'').trim();if(!a)throw new Error('Bitte eine Entscheidung auswählen.');if(a==='comment'){if(!comment)throw new Error('Bitte einen Kommentar eingeben.');await legacy({action:'comment_item',item_id:id,body:comment});}else await legacy({action:a,id,comment});},'task:'+id);}
 function logContact(id){modal('Gespräch dokumentieren',area('Was wurde besprochen?','summary','','required maxlength="500"')+'<p class="muted">Eine Gesprächsnotiz sendet keine Nachricht.</p>',async fd=>api({action:'log_contact',id,summary:fd.get('summary')}),'log:'+id);}
 function openInvoice(id){const i=(state.d.invoices||[]).find(x=>x.id===id);if(!i)return;const team=state.d.role==='team';modal(i.invoice_number,`<p><b>${money(i.gross_cents)}</b> · ${E(i.recipient_name||'Empfänger offen')}</p><p class="muted">Status: ${E(({draft:'Entwurf',sent:'Versendet',paid:'Bezahlt',cancelled:'Storniert',storno:'Storno'})[i.status]||i.status)}</p>${field('Empfängername','recipient_name',i.recipient_name,'text',team&&i.status==='draft'?'required':'readonly')}${area('Anschrift','recipient_address',i.recipient_address,team&&i.status==='draft'?'required':'readonly')}${field('E-Mail','recipient_email',i.recipient_email||i.sent_to,'email',team&&i.status==='draft'?'required':'readonly')}<div class="app-actions">${button('PDF öffnen','pdf',id)}${team&&i.status==='draft'&&state.ready?button('Versand prüfen','send-invoice',id):''}${team&&i.status==='sent'?button('Zahlung verbuchen','paid-invoice',id):''}</div><p class="muted">Vor dem Versand Empfänger und PDF prüfen. Ausgehende Rechnungen werden nur durch das Management versendet.</p>`,team&&i.status==='draft'&&state.ready?async fd=>api({action:'update_invoice_draft',invoice_id:id,...Object.fromEntries(fd)}):null,'invoice:'+id);}
 function createInvoice(gigId){const g=state.d.gigs.find(x=>x.id===gigId);modal('Rechnungsentwurf erstellen',`<p>${E(g.venues?.name||'Auftritt')} · ${date(g.date)}</p>${field('Nettobetrag in €','fee_euros',g.fee??'','number','required min="0.01" step="0.01"')}${field('Empfängername','recipient_name',g.venues?.name,'text','required')}${area('Anschrift','recipient_address','','required')}${field('E-Mail','recipient_email','','email','required')}<p class="muted">Die hinterlegte Steuerregel wird übernommen. Es erfolgt noch kein Versand.</p>`,async fd=>legacy({action:'create_invoice',gig_id:gigId,doc_type:'invoice',...Object.fromEntries(fd),fee_euros:Number(fd.get('fee_euros'))}),'new-invoice:'+gigId);}
 async function pdf(id){try{const r=await fetch(state.ready?API:EP_PDF,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({action:'invoice_pdf',invoice_id:id})});if(!r.ok)throw new Error('PDF konnte nicht erstellt werden.');const blob=await r.blob();if(!blob.type.includes('pdf'))throw new Error('Keine PDF-Antwort erhalten.');const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=(state.d.invoices.find(i=>i.id===id)?.invoice_number||'Rechnung')+'.pdf';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){toast(e.message);}}
 function sendInvoice(id){if(!requiredReady())return;const i=state.d.invoices.find(x=>x.id===id);modal('Rechnung verbindlich versenden',`<p><b>${E(i.invoice_number)}</b> · ${money(i.gross_cents)}</p><p>Empfänger: <b>${E(i.recipient_email||'Noch nicht gespeichert')}</b></p><p class="muted">Es werden die gespeicherten Rechnungsdaten versendet. Änderungen im vorherigen Formular zuerst speichern.</p><label><input type="checkbox" name="confirm" required> Empfänger und PDF geprüft. Diese Rechnung jetzt per E-Mail versenden.</label>`,async fd=>{if(!fd.has('confirm'))throw new Error('Versand bitte bestätigen.');await api({action:'send_invoice_email',invoice_id:id,confirmed_recipient:i.recipient_email});},'send-invoice:'+id);dialog.querySelector('[type=submit]').textContent='Jetzt versenden';}
 function paidInvoice(id){const i=state.d.invoices.find(x=>x.id===id);modal('Zahlung bestätigen',`<p>${E(i.invoice_number)} · ${money(i.gross_cents)}</p><label><input type="checkbox" name="confirm" required> Vollständigen Zahlungseingang geprüft.</label><p class="muted">Diese Aktion markiert die Rechnung als bezahlt. Sie löst keine Banktransaktion aus.</p>`,async()=>legacy({action:'update_invoice_status',invoice_id:id,status:'paid'}));}
 // RFC 4180-style quoted fields; semicolon exports and UTF-8 BOM supported.
 function parseCSV(text){text=text.replace(/^\uFEFF/,'');const first=text.split(/\r?\n/)[0];const delimiter=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(c===delimiter&&!quote){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quote)throw new Error('Nicht geschlossene Anführungszeichen in der CSV.');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;}
 function importContacts(){if(!requiredReady())return;let rows=[];modal('PhantomBuster-Kontakte importieren',`<p class="muted">CSV auswählen, Spalten zuordnen und prüfen. Bekannte E-Mail-Adressen oder Telefonnummern werden übersprungen; vorhandene Kontakte bleiben erhalten. Es wird nichts versendet.</p>${field('Importquelle / Liste','source','PhantomBuster','text','required')}${select('Geprüfte Grundlage der Kontaktdaten','lawful_basis',[['','Bitte prüfen und auswählen'],['existing_relationship','Bestehende Beziehung'],['consent','Einwilligung dokumentiert'],['impressum_published','Veröffentlichte Geschäftsadresse'],['legitimate_interest','Berechtigtes Interesse geprüft'],['contract','Vertragsbeziehung']],'')}<label>CSV-Datei<input id="appCSV" type="file" accept=".csv,text/csv"></label><div id="csvMapping"></div><div id="csvPreview" class="preview-table"></div><p class="muted" id="csvProgress"></p>`,async fd=>{if(!rows.length)throw new Error('Bitte zuerst eine CSV prüfen.');if(!fd.get('lawful_basis'))throw new Error('Bitte Datenherkunft prüfen und Grundlage auswählen.');const headers=rows[0],map=name=>Number(dialog.querySelector('[name="map_'+name+'"]').value);const data=rows.slice(1).map(r=>({name:r[map('name')]||'',email:r[map('email')]||'',phone_whatsapp:r[map('phone')]||'',notes:r[map('notes')]||''}));if(data.some(r=>!r.name||(!r.email&&!r.phone_whatsapp)))throw new Error('Jede Zeile braucht einen Namen und E-Mail oder Telefon. Spalten prüfen.');let n=0,k=0;for(let start=0;start<data.length;start+=50){const result=await api({action:'import_contacts',source:fd.get('source'),lawful_basis:fd.get('lawful_basis'),rows:data.slice(start,start+50)});n+=result.created;k+=result.skipped;dialog.querySelector('#csvProgress').textContent=`${Math.min(start+50,data.length)} / ${data.length} geprüft · ${n} neu · ${k} übersprungen`;}toast(`${n} Kontakte importiert, ${k} übersprungen.`);},'import');
 dialog.querySelector('#appCSV').addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>5*1024*1024)throw new Error('Bitte Dateien unter 5 MB verwenden.');rows=parseCSV(await f.text());if(rows.length<2||rows.length>5001)throw new Error('Datei muss 1 bis 5.000 Kontakte enthalten.');const options=[['-1','Nicht vorhanden'],...rows[0].map((h,i)=>[String(i),h])];const guess=re=>String(rows[0].findIndex(h=>re.test(h)));dialog.querySelector('#csvMapping').innerHTML=select('Name-Spalte','map_name',options,guess(/^(full.?name|name)$/i))+select('E-Mail-Spalte','map_email',options,guess(/email|e-mail/i))+select('Telefon-Spalte','map_phone',options,guess(/phone|telefon|whatsapp/i))+select('Notiz-Spalte','map_notes',options,guess(/notes?|notiz/i));dialog.querySelector('#csvPreview').innerHTML='<p>'+String(rows.length-1)+' Zeilen · Vorschau der ersten 5</p><table><thead><tr>'+rows[0].map(h=>'<th>'+E(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.slice(1,6).map(r=>'<tr>'+r.map(v=>'<td>'+E(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}catch(err){rows=[];dialog.querySelector('.form-error').textContent=err.message;}});}
 async function onClick(e){const b=e.target.closest('[data-app]');if(!b)return;const a=b.dataset.app,id=b.dataset.id;try{
 if(a==='close'){saveDraft();dialog.close();history.replaceState(null,'','#'+state.tab);return;}if(a==='tab')return changeTab(id);if(a==='refresh')return load();
 if(a==='segment'){state.segment=id;return render();}if(a==='book-filter'){state.bookFilter=id;return render();}if(a==='content-filter'){state.contentFilter=id;return render();}if(a==='all-tasks'){state.allTasks=!state.allTasks;return render();}
 if(['contact','gig','content'].includes(a))history.replaceState(null,'','#'+({contact:'contacts',gig:'bookings',content:'content'})[a]+'/'+id);
 if(a==='contact')return openContact(id);if(a==='new-contact')return newContact();if(a==='gig')return openGig(id);if(a==='new-gig')return newGig();if(a==='task')return task(id);if(a==='log')return logContact(id);if(a==='rental')return openRental(id);if(a==='inventory')return inventory();if(a==='content')return openContent(id);if(a==='new-content'||a==='edit-content')return editContent(id);if(a==='publication')return publication(id);if(a==='metric')return metric();if(a==='import')return importContacts();if(a==='invoice')return openInvoice(id);if(a==='new-invoice')return createInvoice(id);if(a==='pdf')return pdf(id);if(a==='send-invoice')return sendInvoice(id);if(a==='paid-invoice')return paidInvoice(id);
 if(a==='rental-invoice'){modal('Mietrechnung erstellen','<p>Ein Rechnungsentwurf wird aus dem gespeicherten Mietpreis erstellt. Kautionen sind nicht im Mietbetrag enthalten.</p>'+field('Empfängername','recipient_name','','text','required')+area('Anschrift','recipient_address','','required')+field('E-Mail','recipient_email','','email','required'),async fd=>api({action:'create_rental_invoice',id,...Object.fromEntries(fd)}),'rental-invoice:'+id);}
 }catch(err){toast(err.message);}}
 // Pure parser exposed solely for the static validation harness, not production data.
 window.WWArtistUtils={parseCSV};
 window.artistOpenInvoice=id=>openInvoice(id);
})();
